sudo: required

services:
- docker

language: cpp
dist: xenial
os: linux

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.bintray.com/igagis/ubuntu xenial main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x379CE192D401AB61'
    update: true
    packages:
    - binfmt-support
    - qemu-user-static
    - myci

matrix:
  include:
    # - name: macosx
    #   os: osx
    #   compiler: clang
    #   osx_image: xcode11
    - name: ios
      os: osx
      compiler: clang
      osx_image: xcode11
    - name: android
      language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-28
#          - sys-img-armeabi-v7a-android-22
          - extra-android-m2repository


env:
  global:
  # Encrypted MYCI_BINTRAY_API_KEY for publishing to bintray.
  - secure: "XW4I94AE58Bj9sGe6GFl/QV6QpT6h2tFutqMWg2Wu3o/9Mtjz8b4bE5l8nUke9o2fm0cfWgIE491URB90PeDo6MTXVsP9GC2XXtOPTh4NkHLAji2BK4kn8U3KlYg+Peneh5lPfEws9uYtAnL3yF0NffT2VktrYx3Fdpnwkha8YkiKEN3TiPLnVZTH/lHqOjZFmkSM7isuW21uahbwpQmLKgiTspzMG1uSlQqaw5Q0w3wk2ay8iv+jKnDRK7iImFCXcV6oEAnJdX6FEvLmwx/htP+7wrKwli9c/mzMrqbz8wbeLbX0mZPoUS5Ro+viU2iz0zFWPVf2uiijMAitFTdKokOC4fNPEvtqkw4yPs2rswjs/BSLyA25YegSBm8T0+sQaAhoAJ8wSURqAl71KizzsKoEvgvnqCO9WM8z7lpSkmMeYieW9Ebn4m6ZrmAL1kxklievodV6jL6raYJXIO3LYgoFc6NZ5lJvvkgDOOuyDQ060kzH0Y216FhvB/N+h6cldrqUVtLdF4Gijgc42uZ7c5FNgSVA8pnZ12Cd9OS1r/SuhDGvWYw91yhKCCXKqrS0GXu2ifktFPmAIjA/OcxQdFXDB3xXw1ePAsz4m9+9rhuhgbVTRyMUoqaWSt7Z7k9uemUX4bmvE+QRrf80BUEXhiY47IYnUqKLfhx0/uucn8="
  # Encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap / cocoapods.
  - secure: "XyFS6UlUeM2ex+V+jawB6IrF4oshELIkqrddUcOGc0OokjLxRkrGaHA2T9yRnzRq1bfTEnF20ijdVHKJAV5J6KSCtzW5secXyHMVm+DCRFenI+AZjZdJgQ0p37WOm7YVm+4kS7UB3asubS2am5JTyfus4wHY8DGhzFDAy47xdw9FaiQ7puMugebz6Ukuxi17kQX5OBw+HQ88TkusGlnNtVLjaXESpNIio4HvjQ+tMNC/TkmjLsyohBa2NyaFqutRf1EORrqkrmehw6vSA43u0i9Xg1ptqZhAuLm4oZ30Io3AQ9fwToG5IbLEV82TmvU03acOd/VVcPw3zpIoNo12XG0q+150sTblNtpt/QXCDUEAqmfpBIjp8QQyg5FAjjcEpd1n/VE/ePXymUspzNrFWideD1pKBfapuZGuU0vvy3ltS5vcNp+rKoOlFnbSlQw9fAExws0ECgG0dgk+VBmLYPOjS7WUCcR8nSz6OkukAoJmBRlbIqTkBXkTYtgWb+J02Nu6zQ3lh8/6a65YLfc/za8DiuX8lQgIIirp3k/19Vp0fqryNYzj25oe/3gBjMgxYbWJ3RRn63tEfAve4Vbh5aXXupC9iVtFWjnvlSD74HOwIow6hC4iPoo4IjRJ/JEwsOtazvN68BoyArqNU3ZmZBjhtkvvkW/gAhxzWVzJT9U="
  - MYCI_GIT_USERNAME=igagis
  - PACKAGE_NAME=pixman
  - PACKAGE_VERSION=$(cat version.txt)
  matrix:
  # - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  # - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  # - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  # - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb


before_install:
# - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
#     docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
#     if [ "$PACKAGE_TYPE" == "deb" ]; then
#       docker exec ccc apt update &&
#       docker exec ccc apt install -y dirmngr &&
#       docker exec ccc bash -c "echo 'deb http://dl.bintray.com/igagis/$OS $OS_REL main' > /etc/apt/sources.list.d/igagis.list" &&
#       docker exec ccc apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
#       docker exec ccc apt update &&
#       docker exec ccc apt install -y devscripts equivs myci &&
#       myci-deb-prepare.sh;
#     fi;
#   fi
# - if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
#     rvm install ruby-2.3.3 &&
#     rvm --default use ruby-2.3.3 &&

#     brew update > /dev/null &&
#     brew tap igagis/tap &&
#     brew update > /dev/null &&
#     brew install prorab prorab-extra myci libutki libpapki libmikroxml;
#   fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    rvm install ruby-2.3.3 &&
    rvm --default use ruby-2.3.3 &&

    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install myci &&

    brew install --force openssl &&

    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$MYCI_GIT_USERNAME:$MYCI_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=xcode;
  fi

install:
# - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
#     docker exec ccc myci-deb-install-build-deps.sh;
#   fi
# Accept android SDK licenses and install android tools
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    echo y | sdkmanager "ndk-bundle" &&
    echo y | sdkmanager "cmake;3.6.4111459";
  fi

before_script:
# - if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
#     curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
#     chmod +x XcodeProjAdder &&
#     (cd xcode/$PACKAGE_NAME && ../../XcodeProjAdder -XCP $PACKAGE_NAME.xcodeproj -SCSV `echo $(find ../../src -type f -name *.cpp) | sed -E -e 's/ /,/g'`)
#   fi

script:
# - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
#     docker exec ccc dpkg-buildpackage -us -uc;
#   fi
# - if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
#     make &&
#     make test;
#   fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    xcodebuild -workspace xcode/$PACKAGE_NAME.xcworkspace -scheme $PACKAGE_NAME CONFIGURATION_BUILD_DIR=../build -configuration Release &&
    myci-create-zip-package.sh -h pixman -f COPKG/config.h///include -f COPKG/pixman-version.h///include -f xcode/build/lib$PACKAGE_NAME.a///lib/ios -f LICENSE $PACKAGE_NAME-$PACKAGE_VERSION.zip;
  fi
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    myci-apply-version.sh -v $PACKAGE_VERSION android/*.pom.in &&
    myci-apply-version.sh -v $PACKAGE_VERSION android/*.aar.in --filename-only;
  fi


before_deploy:

deploy:
# - provider: script
#   skip_cleanup: true
#   on:
#     tags: true
#     condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
#   script: myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: script
  skip_cleanup: true
  script: myci-deploy-maven-bintray.sh -u igagis -r android -d io/github/igagis -p $PACKAGE_NAME -v $PACKAGE_VERSION android/$PACKAGE_NAME-$PACKAGE_VERSION.aar
  on:
    tags: false
    condition: $TRAVIS_JOB_NAME = android
# - provider: script
#   skip_cleanup: true
#   script: myci-deploy-homebrew.sh -t igagis/tap
#   on:
#     tags: true
#     condition: $TRAVIS_JOB_NAME = macosx
- provider: script
  skip_cleanup: true
  script: rvm 2.3.3 do myci-deploy-cocoapods.sh -r igagis -v $PACKAGE_VERSION -u igagis -b cocoapods -p $PACKAGE_NAME-$PACKAGE_VERSION.zip cocoapods/$PACKAGE_NAME.podspec.in
  on:
    tags: false
    condition: $TRAVIS_JOB_NAME = ios
